version: "3"

services:
  client:
    container_name: "Client"
    build: ./real_client
    depends_on:
      - server
    ports:
      - "3000:3000"
  server:
    container_name: "Server"
    build: ./server
    env_file:
    - ./env/express.env
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8080:8080"
  mongodb:
    container_name: "MongoDB"
    image: mongo
    restart: always
    ports:
      - "27017:27017"